language: node_js
node_js:
  - "8"
  - "10"
git:
  depth: 5
cache:
  directories:
    node_modules
install: npm install
before_script:
  - npm install grunt-cli@0.1.13 -g
  - npm install grunt@0.4.5
  - grunt
  - npm install protractor@2.5.1
after_failure: npm install && grunt
matrix:
  fast_finish: true
  